### ISSUE TITLE
Import Error - SLES 12

### ISSUE THREAD

**Issue by snielson** [snielson/dsapp_python#37]
Traceback (most recent call last):
  File "/opt/novell/datasync/tools/dsapp/dsapp.py", line 170, in <module>
    import dsapp_Definitions as ds
  File "/opt/novell/datasync/tools/dsapp/lib/dsapp_Definitions.py", line 11, in <module>
    import subprocess,socket,re,rpm,contextlib
  File "/opt/novell/datasync/tools/dsapp/lib/rpm/__init__.py", line 7, in <module>
    from _rpm import *
ImportError: librpmbuild-4.4.so: cannot open shared object file: No such file or directory

**Comment by snielson** [comment]
Resolved with commit 0c3a122280dfc1360fb303ed03b1cadf47a645b4
Updated v245 release to 245v2

Redownload v245 if already on it.
